version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    allow:
      - dependency-name: ".*"
        dependency-type: "all"
        update-type: "all"