title: "The Relentless Angst"
subtitle: "(Literally just two ravens who've taught themselves to type.)"
description: "An anxious epistolary blog."
url: "https://angst.blog"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
